name: madrasah_management
description: A comprehensive madrasah management system for desktop and mobile platforms with offline capabilities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # State Management
  provider: ^6.0.5
  
  # Navigation
  go_router: ^10.1.2
  
  # UI Components
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_grid_view: ^0.7.0
  
  # File Operations
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # PDF Generation
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # Date/Time
  intl: ^0.18.1
  
  # Encryption
  crypto: ^3.0.3
  
  # Charts and Analytics
  fl_chart: ^0.64.0
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Window Management (Desktop)
  window_manager: ^0.3.7
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
